### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by haziqnorisham** [haziqnorisham/Masatrek#2]
- [x] Add field to filter table data in visitor list
- [x] Show guest image in visitor list
- [ ] Re-activate blacklisted guest from pop-up at gust management home screen
-----------------------------------------
- [ ] Batch download data
